<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Infraestructure\**" />
    <Content Remove="Infraestructure\**" />
    <EmbeddedResource Remove="Infraestructure\**" />
    <None Remove="Infraestructure\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Presentation\ASPNET\wwwroot\css\site.css" />
    <Content Include="Presentation\ASPNET\wwwroot\favicon.ico" />
    <Content Include="Presentation\ASPNET\wwwroot\js\site.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-grid.rtl.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-reboot.rtl.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap-utilities.rtl.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\css\bootstrap.rtl.min.css.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.js.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.bundle.min.js.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.js.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.esm.min.js.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.js.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\dist\js\bootstrap.min.js.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\bootstrap\LICENSE" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation-unobtrusive\dist\jquery.validate.unobtrusive.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation\dist\additional-methods.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation\dist\additional-methods.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation\dist\jquery.validate.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation\dist\jquery.validate.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery-validation\LICENSE.md" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\dist\jquery.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\dist\jquery.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\dist\jquery.min.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\dist\jquery.slim.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\dist\jquery.slim.min.js" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\dist\jquery.slim.min.map" />
    <Content Include="Presentation\ASPNET\wwwroot\lib\jquery\LICENSE.txt" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core\Application\Common\Behaviors\" />
    <Folder Include="Core\Application\Common\CQS\" />
    <Folder Include="Core\Application\Common\Extensions\" />
    <Folder Include="Core\Application\Common\Services\" />
    <Folder Include="Core\Application\Common\Repositories\" />
    <Folder Include="Core\Application\Features\" />
    <Folder Include="Core\Domain\Common\" />
    <Folder Include="Core\Domain\Enums\" />
    <Folder Include="Presentation\ASPNET\BackEnd\Common\Base\" />
    <Folder Include="Presentation\ASPNET\BackEnd\Common\Handlers\" />
    <Folder Include="Presentation\ASPNET\BackEnd\Common\Middlewares\" />
    <Folder Include="Presentation\ASPNET\BackEnd\Common\Models\" />
    <Folder Include="Presentation\ASPNET\BackEnd\Controllers\" />
    <Folder Include="Presentation\ASPNET\FrontEnd\Pages\" />
    <Folder Include="Presentation\ASPNET\Properties\" />
  </ItemGroup>

</Project>
